const authors = [
    {
      "author_no": 1,
      "author_name": 'author_1',
      "university": 'University of Oxford',
      "date_of_birth": '1977-01-01',
      "h_index": 11,
      "gender": 'FEMALE',
      "mentor": 1,
    },
    {
      "author_no": 2,
      "author_name": 'author_2',
      "university": 'California Institute of Technology',
      "date_of_birth": '1976-01-01',
      "h_index": 12,
      "gender": 'MALE',
      "mentor": 4,
    },
    {
      "author_no": 3,
      "author_name": 'author_3',
      "university": 'Stanford University',
      "date_of_birth": '1972-01-01',
      "h_index": 13,
      "gender": 'FEMALE',
      "mentor": 6,
    },
    {
      "author_no": 4,
      "author_name": 'author_4',
      "university": 'Harvard University',
      "date_of_birth": '1978-01-01',
      "h_index": 14,
      "gender": 'MALE',
      "mentor": 4,
    },
    {
      "author_no": 5,
      "author_name": 'author_5',
      "university": 'University of California, Berkeley',
      "date_of_birth": '1980-01-01',
      "h_index": 15,
      "gender": 'FEMALE',
      "mentor": 10,
    },
    {
      "author_no": 6,
      "author_name": 'author_6',
      "university": 'Columbia University',
      "date_of_birth": '1979-01-01',
      "h_index": 1,
      "gender": 'MALE',
      "mentor": 9,
    },
    {
      "author_no": 7,
      "author_name": 'author_7',
      "university": 'University of Toronto',
      "date_of_birth": '1956-01-01',
      "h_index": 2,
      "gender": 'FEMALE',
      "mentor": 7,
    },
    {
      "author_no": 8,
      "author_name": 'author_8',
      "university": 'Cornell University',
      "date_of_birth": '1967-01-01',
      "h_index": 3,
      "gender": 'MALE',
      "mentor": 8,
    },
    {
      "author_no": 9,
      "author_name": 'author_9',
      "university": 'Northwestern University',
      "date_of_birth": '1969-01-01',
      "h_index": 4,
      "gender": 'FEMALE',
      "mentor": 3,
    },
    {
      "author_no": 10,
      "author_name": 'author_10',
      "university": 'University Medical Center New Orleans',
      "date_of_birth": '1955-01-01',
      "h_index": 5,
      'gender': 'MALE',
      "mentor": 1,
    },
    {
      "author_no": 11,
      "author_name": 'author_11',
      "university": 'RWTH Aachen University',
      "date_of_birth": '1966-01-01',
      "h_index": 6,
      "gender": 'FEMALE',
      "mentor": 11,
    },
    {
      "author_no": 12,
      "author_name": 'author_12',
      "university": 'University of California, Irvine',
      "date_of_birth": '1977-01-01',
      "h_index": 7,
      "gender": 'MALE',
      "mentor": 12,
    },
    {
      "author_no": 13,
      "author_name": 'author_13',
      "university": 'University of Zurich',
      "date_of_birth": '1965-01-01',
      "h_index": 8,
      "gender": 'FEMALE',
      "mentor": 14,
    },
    {
      "author_no": 14,
      "author_name": 'author_14',
      "university": 'University of Bristol',
      "date_of_birth": '1980-01-01',
      "h_index": 9,
      "gender": 'MALE',
      "mentor": 13,
    },
    {
      "author_no": 15,
      "author_name": 'author_15',
      "university": 'Sorbonne University',
      "date_of_birth": '1970-01-01',
      "h_index": 10,
      "gender": 'FEMALE',
      "mentor": 15,
    },
  ];

  module.exports = authors;