const authors = [
  {
    author_name: "Carl Sagan",
    university: "Harvard",
    date_of_birth: "1950-9-8",
    h_index: 900,
    gender: "f",
    mentor: 5,
  },
  {
    author_name: "Smol JP",
    university: "Columbia",
    date_of_birth: "1959-10-8",
    h_index: 250,
    gender: "m",
    mentor: 7,
  },
  {
    author_name: "Xie P",
    university: "London",
    date_of_birth: "1953-9-8",
    h_index: 260,
    gender: "f",
    mentor: 6,
  },
  {
    author_name: "Effler SW",
    university: "California",
    date_of_birth: "1956-10-8",
    h_index: 21,
    gender: "m",
    mentor: 12,
  },
  {
    author_name: "Hecky RE",
    university: "Zurich",
    date_of_birth: "1953-9-10",
    h_index: 52,
    gender: "f",
    mentor: 11,
  },
  {
    author_name: "Lotter AF",
    university: "California",
    date_of_birth: "1956-9-8",
    h_index: 75,
    gender: "m",
    mentor: 10,
  },
  {
    author_name: "Wuest A",
    university: "Harvard",
    date_of_birth: "1950-9-8",
    h_index: 30,
    gender: "f",
    mentor: 13,
  },
  {
    author_name: "Jones ML",
    university: "Columbia",
    date_of_birth: "1959-12-8",
    h_index: 86,
    gender: "m",
    mentor: 9,
  },
  {
    author_name: "Imberger J",
    university: "Harvard",
    date_of_birth: "1953-9-12",
    h_index: 78,
    gender: "f",
    mentor: 3,
  },
  {
    author_name: "Cole JJ",
    university: "London",
    date_of_birth: "1956-9-25",
    h_index: 45,
    gender: "m",
    mentor: 4,
  },
  {
    author_name: "Kong FX",
    university: "Yale",
    date_of_birth: "1995-04-26",
    h_index: 10,
    gender: "f",
    mentor: 24,
  },
  {
    author_name: "Jeppesen E",
    university: "Yale",
    date_of_birth: "1956-10-21",
    h_index: 72,
    gender: "m",
    mentor: 14,
  },
  {
    author_name: "Cirpka OA",
    university: "Zurich",
    date_of_birth: "1950-4-10",
    h_index: 10,
    gender: "f",
    mentor: 2,
  },
  {
    author_name: "Rinaldo A",
    university: "Yale",
    date_of_birth: "1959-12-4",
    h_index: 140,
    gender: "m",
    mentor: 8,
  },
  {
    author_name: "Middelburg JJ",
    university: "Zurich",
    date_of_birth: "1953-2-8",
    h_index: 47,
    gender: "f",
    mentor: 15,
  },
];

module.exports = authors;
