const researchPapers =[
  {
    "paper_id": 4,
    "paper_title": "Centers of scientific activity throughout history.",
    "conference": 10,
    "publish_date": "2000" ,
  },
  {
    "paper_id": 6,
    "paper_title": "Life in London in the 15th century",
    "conference": 20,
    "publish_date": "2001" ,
  },
  {
    "paper_id": 8,
    "paper_title": "Mechanisms of thinking: it’s all in your head",
    "conference": 30,
    "publish_date": "2002" ,
  },
  {
    "paper_id": 10,
    "paper_title": "What if aliens do exist: the impact on humanity",
    "conference": 40,
    "publish_date": "2003" ,
  },
  {
    "paper_id": 12,
    "paper_title": "Does Murphy’s Law always work?",
    "conference": 50,
    "publish_date": "2004" ,
  },
  {
    "paper_id": 1,
    "paper_title": "Does meditation have benefits for physical and mental health?",
    "conference": 60,
    "publish_date": "2005" ,
  },
  {
    "paper_id": 3,
    "paper_title": "What is the origin of the modern Santa Claus?",
    "conference": 70,
    "publish_date": "2006" ,
  },
  {
    "paper_id": 5,
    "paper_title": "Culture and literature: which affects which?",
    "conference": 80,
    "publish_date": "2007" ,
  },
  {
    "paper_id": 7,
    "paper_title": "The future of copyright",
    "conference": 90,
    "publish_date": "2008" ,
  },
  {
    "paper_id": 9,
    "paper_title": "How the millennial employee is transforming the workplace",
    "conference": 100,
    "publish_date": "2009" ,
  },
  {
    "paper_id": 12,
    "paper_title": "Should businesses be regulated: pros and cons",
    "conference": 110,
    "publish_date": "2010" ,
  },
  {
    "paper_id": 14,
    "paper_title": "Overtime work, employee well-being, and company performance.",
    "conference": 120,
    "publish_date": "2011" ,
  },
  {
    "paper_id": 16,
    "paper_title": "How does outsourcing influence business performance?",
    "conference": 130,
    "publish_date": "2012" ,
  },
  {
    "paper_id": 18,
    "paper_title": "Social media marketing strategies and the determinants of success.",
    "conference": 140,
    "publish_date": "2013" ,
  },
  {
    "paper_id": 20,
    "paper_title": "Theories regarding the Bermuda triangle",
    "conference": 150,
    "publish_date": "2014" ,
  },
  {
    "paper_id": 13,
    "paper_title": "The future of NASA",
    "conference": 160,
    "publish_date": "2015" ,
  },
  {
    "paper_id": 15,
    "paper_title": "Nuclear weapons: a responsibility for which no country is prepared",
    "conference": 170,
    "publish_date": "2016" ,
  },
  {
    "paper_id": 17,
    "paper_title": "Deafness and using echolocation",
    "conference": 180,
    "publish_date": "2017" ,
  },
  {
    "paper_id": 19,
    "paper_title": "Will uranium isotopes precipitate the next scientific revolution?",
    "conference": 190,
    "publish_date": "2018" ,
  },
  {
    "paper_id": 21,
    "paper_title": "Human dependence on computers: beneficial or harmful",
    "conference": 200,
    "publish_date": "2019" ,
  },
  {
    "paper_id": 22,
    "paper_title": "Political commitment and television",
    "conference": 210,
    "publish_date": "2020" ,
  },
  {
    "paper_id": 24,
    "paper_title": "The function of technology in lesson planning",
    "conference": 220,
    "publish_date": "2021" ,
  },
  {
    "paper_id": 26,
    "paper_title": "How to prevent bullying and harassment in schools",
    "conference": 230,
    "publish_date": "1999" ,
  },
  {
    "paper_id": 28,
    "paper_title": "The mental process behind human learning",
    "conference": 240,
    "publish_date": "1998" ,
  },
  {
    "paper_id": 30,
    "paper_title": "The effects of contemporary teaching methods",
    "conference": 250,
    "publish_date": "1997" ,
  },
  {
    "paper_id": 23,
    "paper_title": "Evaluating the challenges of preterm development in children",
    "conference": 260,
    "publish_date": "1996" ,
  },
  {
    "paper_id": 25,
    "paper_title": "How to fight emotional distress",
    "conference": 270,
    "publish_date": "1995" ,
  },
  {
    "paper_id": 27,
    "paper_title": "How depression impacts the immune system",
    "conference": 280,
    "publish_date": "1994" ,
  },
  {
    "paper_id": 29,
    "paper_title": "Why people yearn for their past",
    "conference": 290,
    "publish_date": "1993" ,
  },
  {
    "paper_id": 31,
    "paper_title": "Mechanisms of aggravating habits",
    "conference": 300,
    "publish_date": "1992" ,
  }
]
  
  module.exports = researchPapers;